



- name: Install Redis repo on CentOS-8
  ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y --skip-broken
  ignore_errors: true  

- name: Install Redis module
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y


- name: Install the  redis package
  ansible.builtin.yum:
    name: redis
    state: present

- name: Stop the service
  ansible.builtin.systemd:
    name: redis
    state: stopped 
  ignore_errors: true      


- name: Replace loop back address 127.0.0.1 with 0.0.0.0 on Redis config 
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'  

- name: Enable and start the service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: true    
    daemon_reload: yes          

# echo " Install Redis repo on CentOS-8"
# dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y --skip-broken &>>$LOG_FILE
# Statuscheck $?

# echo " Install Redis on CentOS-8"
# dnf module enable redis:remi-6.2 -y
# yum install redis -y &>>$LOG_FILE
# Statuscheck $?

# echo "stopping  redis "
# systemctl stop redis &>>$LOG_FILE
# Statuscheck $?

# echo "Update the bind from 127.0.0.1 to 0.0.0.0"
# sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/redis.conf &>>$LOG_FILE
# Statuscheck $?

# echo "enabling redis "
# systemctl enable redis &>>$LOG_FILE
# Statuscheck $?


# echo "starting redis "
# systemctl start redis &>>$LOG_FILE
# Statuscheck $?





