- name: Download mongodb repo file and place it a directory
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo


- name: Install the  MongoDB package
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: Enable and start the service
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true    
    daemon_reload: yes    


- name: Replace loop back address 127.0.0.1 with 0.0.0.0 on MongoDB config 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


- name: Restart the MongoDB service
  ansible.builtin.systemd:
    name: mongod
    state: restarted


- name: Recursively remove file
  ansible.builtin.file:
    path: 
      - /tmp/mongodb.zip
      - /tmp/mongodb
    state: absent
    force: true 

- name: Recursively remove directory
  ansible.builtin.file:
    path: /tmp/mongodb-main
    state: absent    
    force: true


# echo "Download the schema and load it."
# rm -rf /tmp/mongodb.zip
# rm -rf /tmp/mongodb-main
# curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip" &>>${LOG_FILE}
# Statuscheck $?

# echo "load the data into mongodb"
# cd /tmp
# unzip mongodb.zip &>>${LOG_FILE}
# Statuscheck $?
# cd mongodb-main
# mongo < catalogue.js &>>${LOG_FILE}
# Statuscheck $?
# mongo < users.js &>>${LOG_FILE}
# Statuscheck $?
