- name: Import common role and run maven task 
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Import rsyslog role
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog       