# - name: Frontend node setup 
#   hosts: FRONTEND
#   become: true  
#   roles:
#     - frontend

# - name: Mongodb  setup 
#   hosts: MONGODB
#   become: true  
#   roles:
#     - mongodb    

# - name: Catalogue  setup 
#   hosts: CATALOGUE
#   become: true  
#   roles:
#     - catalogue        


# - name: USER  setup 
#   hosts: USER
#   become: true  
#   roles:
#     - user  


# - name: CART setup 
#   hosts: CART
#   become: true  
#   roles:
#     - cart          


- name: USER  setup 
  hosts: USER
  become: true  
  roles:
    - user  


- name: CART setup 
  hosts: CART
  become: true  
  roles:
    - cart    

- name: USER  setup 
  hosts: USER
  become: true  
  roles:
    - user         