# - name: Frontend node setup 
#   hosts: FRONTEND
#   become: true  
#   roles:
#     - frontend

# - name: Mongodb  setup 
#   hosts: MONGODB
#   become: true  
#   roles:
#     - mongodb    

# - name: Catalogue  setup 
#   hosts: CATALOGUE
#   become: true  
#   roles:
#     - catalogue        


# - name: USER  setup 
#   hosts: USER
#   become: true  
#   roles:
#     - user  


# - name: CART setup 
#   hosts: CART
#   become: true  
#   roles:
#     - cart          


- name: SHIPPING setup 
  hosts: SHIPPING
  become: true  
  roles:
    - maven  


- name: PAYMENT setup 
  hosts: PAYMENT
  become: true  
  roles:
    - python    

- name: DISPATCH setup 
  hosts: DISPATCH
  become: true  
  roles:
    - golang         