- name: Import common role and run python task 
  ansible.builtin.include_role:
    name: common
    tasks_from: python

- name: Import rsyslog role
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog     

- name: Import filebeat  role
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat        