
- name: Remove the Nginx package
  ansible.builtin.yum:
    name: nginx
    state: absent
  ignore_errors: true  

- name: Recursively remove directory
  ansible.builtin.file:
    path: /etc/nginx/*
    state: absent


- name: Install the  Nginx package
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Enable and start the service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true    


- name: Download file and place it a directory
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip


- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

# echo "Let's download the HTDOCS content and deploy under the Nginx path."
# rm -rf /tmp/frontend.zip
# curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip" &>>${LOG_FILE}
# Statuscheck $?

# echo "Deploy the downloaded content in Nginx Default Location."
# cd /usr/share/nginx/html
# rm -rf *
# unzip /tmp/frontend.zip
# mv frontend-main/static/* .
# mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf  &>>${LOG_FILE}
# Statuscheck $?



# echo " Updating the systemD service file with DNS name"
# sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${LOG_FILE}
# Statuscheck $?
# sed -i -e '/user/ s/localhost/user.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${LOG_FILE}
# Statuscheck $?
# sed -i -e '/cart/ s/localhost/cart.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${LOG_FILE}
# Statuscheck $?
# sed -i -e '/shipping/ s/localhost/shipping.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${LOG_FILE}
# Statuscheck $?
# sed -i -e '/payment/ s/localhost/payment.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${LOG_FILE}
# Statuscheck $?

# echo "Finally restart the service once to effect the changes"

# systemctl restart nginx &>>${LOG_FILE}
# Statuscheck $?
