




- name: Download Rabbitmq repo on CentOS-8
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Download erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash


- name: Install the  rabbitmq-server package
  ansible.builtin.yum:
    name: rabbitmq-server 
    state: present

- name: Enable and start the service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: true    
    daemon_reload: yes  


- name: Adding user to rabbitmq and setting the permissions
  community.rabbitmq.rabbitmq_user:
    user: "{{RABBITMQ_USER}}"
    password: "{{RABBITMQ_PASSWORD}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator


rabbitmqctl list_users | grep -i roboshop &>>$LOG_FILE
if [ $? ne 0 ]; then 
    echo "adding roboshop user to rabbitmq"
    rabbitmqctl add_user roboshop roboshop123 &>>$LOG_FILE
    Statuscheck $?
fi

echo " set roboshop user in rabbitmq as administrator"
rabbitmqctl set_user_tags roboshop administrator &>>$LOG_FILE
Statuscheck $?
rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>$LOG_FILE
Statuscheck $?