- name: Copy logstash
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf


- name:  restart the service logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    daemon_reload: yes    

  