- name: Import rsyslog role
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog   

- name: Import logstash role
  ansible.builtin.include_role:
    name: elk
    tasks_from: logstash       