# copy the config file - //etc/ryslog.d/
# restart the service 

- name: Copy rsyslog file to seperate the logs from messages
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/rsyslog.d/roboshop.conf


- name:  restart the service rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    daemon_reload: yes    

- name:  restart the {{COMPONENT}}
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    daemon_reload: yes      