

- name: Install mysql repo on CentOS-8
  ansible.builtin.shell: curl -s -L -o /etc/yum.repos.d/mysql.repo https://raw.githubusercontent.com/roboshop-devops-project/mysql/main/mysql.repo
  ignore_errors: true  


- name: disable mysql module
  ansible.builtin.shell: dnf module disable mysql
  ignore_errors: true


- name: Install the  redis package
  ansible.builtin.yum:
    name: mysql-community-server
    state: present


- name: Enable and start the service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true    
    daemon_reload: yes 

- name: DEFAULT_PASSWORD 
  ansible.builtin.shell: grep 'A temporary password' /var/log/mysqld.log | cut -d " " -f 11
  register: out 

- name: get the uptime data from defined variable
  ansible.builtin.debug:
   msg: "{{out.stdout}}"  

- name: Copy file 
  ansible.builtin.copy:
    src: set-root-passwd.sql
    dest: /tmp/

- name: validate wheather we were able to connect uisng the default password 
  ansible.builtin.shell: mysql --connect-expired-password -uroot -p{{out.stdout}} < /tmp/set-root-passwd.sql 
  ignore_errors: true
  register: mysql_conn_status

- name: validate wheather we were able to connect uisng the set password 
  ansible.builtin.shell: echo "show databases;" | mysql --connect-expired-password -uroot -p{{ROBOSHOP_MYSQL_PASSWORD}}
  ignore_errors: true
  when: mysql_conn_status is failed



- name: Recursively remove directory
  ansible.builtin.file:
    path: 
      - "/tmp/mysql.zip"
      - "/tmp/mysql-main"
    state: absent
  ignore_errors: yes   

- name: Download file and place it a directory
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/mysql/archive/main.zip
    dest: /tmp/mysql.zip

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/mysql.zip
    dest: /tmp
    remote_src: yes

- name: validate wheather we were able to connect uisng the default password 
  ansible.builtin.shell: mysql --connect-expired-password -uroot -p{{ROBOSHOP_MYSQL_PASSWORD}} < /tmp/mysql-main/shipping.sql



- name: Import common role and run promethus-node task 
  ansible.builtin.include_role:
    name: common
    tasks_from: promethus-node  

