- name: Import common role and run golang task 
  ansible.builtin.include_role:
    name: common
    tasks_from: golang

- name: Import rsyslog role
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog       