

- name: Install the  Golang package
  ansible.builtin.yum:
    name: golang
    state: present

- name: Apply App-prereq.yml 
  ansible.builtin.include_tasks: app-prereq.yml 

- name: Setup golang and install dependencies 
  ansible.builtin.shell: go mod init dispatch &&  go get && go build
  args:
    chdir: /home/roboshop/{{COMPONENT}} 
  become_user: roboshop  

- name: Apply systemd.yml 
  ansible.builtin.include_tasks: systemd.yml   

- name: Apply promethus node-exporter 
  ansible.builtin.include_tasks: promethus-node.yml 


# GOLANG() {

#     echo " Installing golang "
#     yum install golang -y &>>${LOG_FILE}
#     Statuscheck $?

#     APP_PREREQ

#     echo " Installing the dependencies "
#     cd /home/roboshop
#     cd ${COMPONENT}
#     #cd /home/${COMPONENT}/
#     go mod init dispatch &>>${LOG_FILE}
#     Statuscheck $?

#     echo "Doing the golang build"
#     go get 
#     go build &>>${LOG_FILE}
#     Statuscheck $?

#     SYSTEMD_SETUP

# }