- name: Install the  python package
  ansible.builtin.yum:
    name: 
     - python36
     - gcc
     - python3-devel
    state: present

- name: Apply App-prereq.yml 
  ansible.builtin.include_tasks: app-prereq.yml 

- name: Setup python and install dependencies 
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /home/roboshop/{{COMPONENT}} 
  become_user: roboshop  

- name: Apply systemd.yml 
  ansible.builtin.include_tasks: systemd.yml   

- name: Apply promethus node-exporter 
  ansible.builtin.include_tasks: promethus-node.yml 


# PYTHON() {

#     echo " Installing Python on the VM "
#     yum install python36 gcc python3-devel -y  &>>${LOG_FILE}
#     Statuscheck $?

#     APP_PREREQ

#     echo " Installing the dependencies "
#     cd /home/roboshop
#     cd ${COMPONENT}
#     #cd /home/${COMPONENT}/ 
#     pip3 install -r requirements.txt &>>${LOG_FILE}
#     Statuscheck $?

#     SYSTEMD_SETUP


# }
