PYTHON() {

    echo " Installing Python on the VM "
    yum install python36 gcc python3-devel -y  &>>${LOG_FILE}
    Statuscheck $?

    APP_PREREQ

    echo " Installing the dependencies "
    cd /home/roboshop
    cd ${COMPONENT}
    #cd /home/${COMPONENT}/ 
    pip3 install -r requirements.txt &>>${LOG_FILE}
    Statuscheck $?

    SYSTEMD_SETUP


}
